package org.sl.utils.avro.validator

class ValidatorException(message: String, cause: Throwable) : RuntimeException(message, cause)
